---
- name: install pyOpenSSL package from pip
  pip:
    name: pyOpenSSL==19.0.0
    state: forcereinstall

- name: install openssl and pip
  yum:
    name: openssl

- name: create a dummy private key
  openssl_privatekey:
    path: /etc/pki/tls/private/{{ ansible_fqdn }}.key

- name: create a csr
  openssl_csr:
    path: /etc/pki/tls/private/{{ ansible_fqdn }}.csr
    privatekey_path: /etc/pki/tls/private/{{ ansible_fqdn }}.key
    common_name: "{{ ansible_fqdn }}"

- name: create a self signed cert
  openssl_certificate:
    path: /etc/pki/tls/certs/{{ ansible_fqdn }}.crt
    privatekey_path: /etc/pki/tls/private/{{ ansible_fqdn }}.key
    csr_path: /etc/pki/tls/private/{{ ansible_fqdn }}.csr
    provider: selfsigned
